#sdk: "/Users/mva/.rvm/gems/ruby-1.9.3-p551/gems/rhodes-5.5.0.8"
sdkversion: 5.5.0
name: inventoryDemo
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
#javascript_application: true
iphone:
  configuration: Release
  sdk: latest
  #provisionprofile:
  #codesignidentity:
  #entitlements:
  BundleIdentifier: com.tautechnologies.inventorydemo
  BundleURLScheme: inventorydemo
  info_plist_data:
    NSAppTransportSecurity:
      NSAllowsArbitraryLoads: true
  extensions:
    - "barcode"

wp8:
  productid: '07c45400-ba39-0134-a27f-60f81db5e3c0'
  extensions:
    - enterprise-barcode

android:
  manifest_template: 'AndroidManifest.erb'
  version: 4.1.0
  android_title: 0
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
  extensions:
    #- enterprise-barcode

wm:
  extensions:
    - enterprise-barcode
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

win32:
  deployqt: 1
  deploymsvc: 1
  extensions:
    - enterprise-barcode

extensions:
  - rhoconnect-client
  - barcode
  - mediacapture
  - signature

rhobundle:
  exclude_items:
  - thumb.db
